version: '3'
services:
    web:
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: bash ./start.dev.sh
        #networks:
            #- webnet
        expose:
            - 8000
        # ports:
        #     - 8000:8000
        depends_on:
            - db
        environment:
            DEBUG: 'True'
            NAME_DB: postgres
            USER_NAME: postgres
            USER_PW: postgres
            HOST: db
            PORT: 5432
            # DATABASE_URL: 'postgres://postgres:@db:5432/postgres'

    db:
        image: postgres:11.2
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        #networks: 
            #- webnet
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
    nginx:
        build: ./nginx
        #networks:
            #- webnet
        ports:
            - 80:80
            - 443:443
        depends_on:
            - web
#networks:
    #webnet:
