version: '3'
services:
    server:
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: bash ./start.sh
        ports:
            - 80:8000
        depends_on:
            - db
        environment:
            DEBUG: 'True'
            NAME_DB: postgres
            USER_NAME: postgres
            USER_PW: postgres
            HOST: db
            PORT: 5432
            # DATABASE_URL: 'postgres://postgres:@db:5432/postgres'

    db:
        image: postgres:11.2
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
