# Generated by Django 3.1.2 on 2020-10-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_authtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='isAuthenticated',
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
