# Generated by Django 3.1.2 on 2020-10-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201024_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='isAuthenticated',
            field=models.BooleanField(default=True),
        ),
    ]
