# Generated by Django 3.1.2 on 2020-10-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auth_isauthenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='isAuthenticated',
        ),
    ]
