# Generated by Django 3.1.2 on 2020-10-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_auth_isauthenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
